### ISSUE TITLE
Errror when starting "Run container in browser"

### ISSUE THREAD

**Issue by louisvangeldrop** [ktock/vscode-container-wasm#17]
The command: "Run Container in Browser" results in:

WebAssembly.compile(): expected magic word 00 61 73 6d, found 5b 22 68 74 @+0

**Comment by ktock** [comment]
@louisvangeldrop Thanks for reporting the issue. Could you provide the version of vscode-container-wasm installed to your editor and `.vscode/settings.json` to reproduce the issue?

**Comment by louisvangeldrop** [comment]
vscode-container-wasm v0.0.2.

{
    "workbench.sideBar.location": "right",
    "workbench.startupEditor": "none",
    "devicescript.devtools.node": "C:\\Program Files\\nodejs",
    "devicescript.devtools.internet": true,
    "devicescript.devtools.developerMode": true,
    "cmake.showOptionsMovedNotification": false,
    "git.enableSmartCommit": true,
    "git.confirmSync": false,
    "git.autofetch": true,
    "cmake.configureOnOpen": false,
    "arduino.useArduinoCli": true,
    "security.workspace.trust.untrustedFiles": "open",
    "editor.insertSpaces": false,
    "terminal.integrated.profiles.windows": {
        "PowerShell": {
            "source": "PowerShell",
            "icon": "terminal-powershell"
        },
        "Command Prompt": {
            "path": [
                "${env:windir}\\Sysnative\\cmd.exe",
                "${env:windir}\\System32\\cmd.exe"
            ],
            "args": [],
            "icon": "terminal-cmd"
        },
        "Git Bash": {
            "source": "Git Bash"
        },
        "VS 2022 Command Prompt": {
            "path": "${env:windir}\\System32\\cmd.exe",
            "args": [
                "/k",
                "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\Common7\\Tools\\VsDevCmd.bat",
                "-startdir=none",
                "-arch=x64",
                "-host_arch=x64"
            ]
        },
        "VS 2022 Moddable": {
            "path": "${env:windir}\\System32\\cmd.exe",
            "args": [
                "/k",
                "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\Common7\\Tools\\VsDevCmd.bat",
                "-startdir=none",
                "-arch=x64",
                "-host_arch=x64",
                "&&",
                "%idf_path%\\export.bat"
            ]
        }
    },
    "terminal.integrated.defaultProfile.windows": "PowerShell",
    "[typescript]": {
        "editor.defaultFormatter": "vscode.typescript-language-features"
    },
    "[javascript]": {
        "editor.defaultFormatter": "vscode.typescript-language-features"
    },
    "terminal.integrated.enableMultiLinePasteWarning": false,
    "git.openRepositoryInParentFolders": "always",
    "idf.espIdfPathWin": "C:\\Users\\louis\\esp\\esp-idf",
    "idf.pythonBinPathWin": "C:\\Users\\louis\\.espressif\\python_env\\idf5.1_py3.11_env\\Scripts\\python.exe",
    "idf.toolsPathWin": "C:\\Users\\louis\\.espressif",
    "idf.customExtraPaths": "C:\\Users\\louis\\.espressif\\tools\\xtensa-esp-elf-gdb\\12.1_20221002\\xtensa-esp-elf-gdb\\bin;C:\\Users\\louis\\.espressif\\tools\\riscv32-esp-elf-gdb\\12.1_20221002\\riscv32-esp-elf-gdb\\bin;C:\\Users\\louis\\.espressif\\tools\\xtensa-esp32-elf\\esp-12.2.0_20230208\\xtensa-esp32-elf\\bin;C:\\Users\\louis\\.espressif\\tools\\xtensa-esp32s2-elf\\esp-12.2.0_20230208\\xtensa-esp32s2-elf\\bin;C:\\Users\\louis\\.espressif\\tools\\xtensa-esp32s3-elf\\esp-12.2.0_20230208\\xtensa-esp32s3-elf\\bin;C:\\Users\\louis\\.espressif\\tools\\riscv32-esp-elf\\esp-12.2.0_20230208\\riscv32-esp-elf\\bin;C:\\Users\\louis\\.espressif\\tools\\esp32ulp-elf\\2.35_20220830\\esp32ulp-elf\\bin;C:\\Users\\louis\\.espressif\\tools\\cmake\\3.24.0\\bin;C:\\Users\\louis\\.espressif\\tools\\openocd-esp32\\v0.12.0-esp32-20230419\\openocd-esp32\\bin;C:\\Users\\louis\\.espressif\\tools\\ninja\\1.10.2;C:\\Users\\louis\\.espressif\\tools\\idf-exe\\1.0.3;C:\\Users\\louis\\.espressif\\tools\\ccache\\4.8\\ccache-4.8-windows-x86_64;C:\\Users\\louis\\.espressif\\tools\\dfu-util\\0.11\\dfu-util-0.11-win64;C:\\Users\\louis\\.espressif\\tools\\esp-rom-elfs\\20230320",
    "idf.customExtraVars": {
        "OPENOCD_SCRIPTS": "C:\\Users\\louis\\.espressif\\tools\\openocd-esp32\\v0.12.0-esp32-20230419/openocd-esp32/share/openocd/scripts",
        "IDF_CCACHE_ENABLE": "1",
        "ESP_ROM_ELF_DIR": "C:\\Users\\louis\\.espressif\\tools\\esp-rom-elfs\\20230320/"
    },
    "idf.gitPathWin": "C:\\Users\\louis\\.espressif\\tools\\idf-git\\2.39.2\\cmd\\git.exe",
    "vsicons.dontShowNewVersionMessage": true,
    "[jsonc]": {
        "editor.defaultFormatter": "vscode.json-language-features"
    },
    "editor.formatOnSave": true,
    "[json]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "workbench.editor.enablePreview": false
}

**Comment by ktock** [comment]
@louisvangeldrop  To launch a container on vscode, you need to set at least `container.imageLocation` (or `container.containerImage`) to the image location. 

- docs: https://github.com/ktock/vscode-container-wasm/tree/1919e5fade95014d9030a912a6b3f9b2682045bf?tab=readme-ov-file#extension-settings
- example repo: https://github.com/ktock/vscode-container-wasm-gcc-example

**Comment by louisvangeldrop** [comment]
Thx for the update. The example repo works now

**Comment by ktock** [comment]
Thanks for testing that. Closing this issue as it works now.
