### ISSUE TITLE
No reflect file changes by editor in container terminal

### ISSUE THREAD

**Issue by goofmint** [ktock/vscode-container-wasm#18]
This is incredible work!

When I change or create a file in the container terminal like the one below.

```bash
echo "bbb" > test2.md
```

It showed a new file named test2.md in the editor's file tree.

<img width="287" alt="image" src="https://github.com/ktock/vscode-container-wasm/assets/5709/b4243ae9-483d-4916-ba90-45cd508f4c1e">

After that, I updated and saved the file content in the editor. 

```md
aaa
bbb
```

However, the terminal doesn't reflect changes.

```bash
# cat test2.md 
bbb
```

How can I update the file in a container?

Env:

- macOS 14.3.1
- Google Chrome 121.0.6167.184（Official Build） （arm64）

**Comment by ktock** [comment]
@goofmint Thanks for reporting this issue. This has been fixed in v0.0.3. Please try the latest version.

**Comment by goofmint** [comment]
@ktock Thank you so much! It works perfectly!
